### ISSUE TITLE
Mask disappears instead of possessing the player.

### ISSUE THREAD

**Issue by SpazzMaticus107** [RealPlanet/MaskTheDead#1]
The mask doesn't work. It dispawns when trying to possess a player. It gets on his face and then is removed from his inventory and just vanishes from his screen. The possessed will still spawn when the mask is dropped on the ground but it can no longer be effectively put on with left click when in hand. That's broken.

Steps to reproduce.

1. Spawn in
2. Spawn one of the masks or find one
3. Try to put it on
4. Watch it disappear in front of your eyes

**Comment by RealPlanet** [comment]
Hello, thanks for the report.
I pushed a new version of the mod (V 1.0.4) that should fix this problem.
I tested it locally with two players and seemed to work fine but please let me know if there's any more issues

**Comment by SpazzMaticus107** [comment]
Tested with a friend. Seems to be working with no issues. Thanks for the quick fix.
