### ISSUE TITLE
Infinite masked

### ISSUE THREAD

**Issue by VanilaBOI** [RealPlanet/MaskTheDead#2]
I have had a problem where when someone killed them self with the killbind mod and also have a mask they would make two masked.
This is totally not a big problem but when someone died on the ship with mask items around them, they would make hundreds of masked.

[LogOutput.log](https://github.com/RealPlanet/MaskTheDead/files/13799229/LogOutput.log)
IDK if this helps

![image](https://github.com/RealPlanet/MaskTheDead/assets/86358160/700ad4c5-187e-4ec8-9643-9923ae3edacd)

**Comment by RealPlanet** [comment]
Hi a possible fix has been implemented (1.0.5). Please let me know how it goes.

**Comment by RealPlanet** [comment]
I'll assume it is fixed

**Comment by VanilaBOI** [comment]
Well ot hasn't happened again so yeah 👍
