### ISSUE TITLE
Chat is this real

### ISSUE THREAD

**Issue by ImpulsiveLass** [RealPlanet/MaskTheDead#4]
So there is possession chance, retry possession time, and mask possession range.
The last is very clear.

If possession change is 0.2 and the RPT is 5000 miliseconds. That would mean that every 5 seconds the mask attempts to posses a body right?

Or does 0.2 chance mean that it tries once and only a 5th of the time there is an available body it will be possessed?

![Screenshot 2024-01-05 221448](https://github.com/RealPlanet/MaskTheDead/assets/92990441/af0fc196-e3e2-4211-bcb2-45a2949dc90e)
Also typo :)

**Comment by RealPlanet** [comment]
Hi, it means that every 5 seconds there will be a 0.2 canche that a nearby body will be possessed. The timer stops if no body is present. I will fix the typo with the next patch
