### ISSUE TITLE
[New(?) feature+boolean for it]

### ISSUE THREAD

**Issue by ImpulsiveLass** [RealPlanet/MaskTheDead#5]
Haven't tested too much since I haven't seen the mod in use in multiplayer yet.

Can the mask possess ALL bodies or does it have some exclusions like coilhead kills, spider wrapped bodies etc.

If so then will the mask heal itself over to seem healthy again or would you end up having a headless zombie or at least a blood drenched masked.

If this isn't in there mod already then It would be nice if it was added and could be enabled/disabled by config.

My pack goes full into the masked being zombies idea so it this would work deliciously with it.

**Comment by RealPlanet** [comment]
The mask looks for any ragdoll nearby then calls the official code for the mimic, which deletes the ragdoll and spawns a mimic based on the original player

**Comment by ImpulsiveLass** [comment]
Ok so it doesn't keep damage, I am guessing the mod is compatible with maskedenemyoverhaul?

**Comment by RealPlanet** [comment]
Should be.
