### ISSUE TITLE
Adding a initial delay before trying to possess (for compatibility with TakeThatMaskOff)

### ISSUE THREAD

**Issue by PickeBlind** [RealPlanet/MaskTheDead#6]
The way the two mods currently work is that after killing a possessed player, TakeThatMaskOff will drop the mask and player body, and MaskTheDead will possess it again almost immediately. Is there a way to make it so that there's a initial delay before a possession attempt, so that you can retrieve the mask before it occurs? At least that's one way I thought of fixing it, you probably will have better ones

**Comment by RealPlanet** [comment]
I added a delay like you requested, by default it will be disabled, you just need to set a time amount higher than zero. Look out for the next update
